---
- name: Create .ssh directory for root
  become: yes
  file:
    path: '/root/.ssh'
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,g=,o='

- name: Add ssh keys for admin users to user root
  template:
    src: 'authorized_keys.j2'
    dest: '/root/.ssh/authorized_keys'
    owner: root
    group: root
    mode: 'u=rw,g=,o='
  become: yes

- name: Add admin group
  group:
    name: 'admins'
    state: present
  become: yes

- name: Add admin users
  user:
    name: '{{ item }}'
    shell: '/bin/bash'
    groups: 'admins'
    append: yes
  with_items: '{{ admins }}'
  become: yes

- name: Create .ssh directory for all admin users
  file:
    path: '/home/{{ item }}/.ssh'
    state: directory
    owner: '{{ item }}'
    group: admins
    mode: 'u=rwx,g=,o='
  with_items: '{{ admins }}'
  become: yes

- name: Add ssh keys for admin users to their users
  copy:
    src: 'files/{{ admin_ssh_keys }}/{{ item }}_id.pub'
    dest: '/home/{{ item }}/.ssh/authorized_keys'
    owner: '{{ item }}'
    group: admins
    mode: 'u=rw,g=,o='
  with_items: '{{ admins }}'
  become: yes

- name: Add ansible user
  user:
    name: 'ansible'
    shell: '/bin/bash'
    groups: 'admins'
    append: yes
  become: yes

- name: Create .ssh directory for user ansible
  file:
    path: '/home/ansible/.ssh'
    state: directory
    owner: ansible
    group: admins
    mode: 'u=rwx,g=,o='
  become: yes

- name: Add ssh keys for admins to user ansible
  template:
    src: 'authorized_keys.j2'
    dest: '/home/ansible/.ssh/authorized_keys'
    owner: ansible
    group: admins
    mode: 'u=rw,g=,o='
  become: yes

- name: Copy .bashrc for user ansible
  copy:
    src: 'files/home_environment/bashrc'
    dest: '/home/ansible/.bashrc'
    owner: ansible
    group: admins
    mode: 'u=rw,g=r,o='
  become: yes

- name: Create /etc/sudoers.d directory
  file:
    path: '/etc/sudoers.d'
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,g=x,o=x'
  become: yes

- name: Copy sudoers file
  copy:
    src: 'files/home_environment/sudoers'
    dest: '/etc/sudoers.d/ansible'
    owner: root
    group: root
    mode: 'u=r,g=r,o='
  become: yes

