---

- name: Extract local and remote user names
  set_fact:
    local_user: '{{ local_user_data.key }}'
    remote_users: '{{ local_user_data.value }}'

- name: 'Setup .ssh for user {{ local_user }}'
  become: yes
  file:
    path: '/home/{{ local_user }}/.ssh/'
    state: directory
    owner: '{{ local_user }}'
    group: '{{ local_user }}'
    mode: 'u=rwx,g=,o='

- name: 'Add ssh keys for user {{ local_user }}'
  become: yes
  template:
    src: authorized_keys.j2
    dest: '/home/{{ local_user }}/.ssh/authorized_keys'
    owner: '{{ local_user }}'
    group: '{{ local_user }}'
    mode: 'u=rw,g=,o='

